### ISSUE TITLE
Clearer setup instructions needed.

### ISSUE THREAD

**Issue by pykong** [kaste/SublimeLinter-addon-black-for-flake#2]
@kaste  I have found this neat little plugin really helpful, thanks!

One small issue: I was not able to make it work until adding `"SublimeLinter-addon-black-for-flake.enable": true` to my settings. I do not know whether this is a bug or intended. In the latter case the `README` should provide clearer more explicit setup instructions.
Like:
1. Install `sublack` via packagecontrol
2. Install `"SublimeLinter-addon-black-for-flake.enable": true` via packagecontrol
3. Set sublack to ` "black_on_save": true`
4. In Preferences or Python syntax specific prefs set: `"SublimeLinter-addon-black-for-flake.enable": true`

**Comment by kaste** [comment]
In the Readme I provide an example project file you can basically copy and paste. 

I wouldn't recommend to set this globally like you do as long as black is not used by more projects.

**Comment by pykong** [comment]
OK. Everything is alright then.
